<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGEK72W4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGEK72W4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGEK72W4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGEK72W4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGEK72W4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GEK72W4',
    'container.build_id' => 'bf7bed86',
    'container.build_time' => 1559907249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGEK72W4');
